#cloud-config
users:
  - name: ubuntu
    sudo: ALL=(ALL) NOPASSWD:ALL
    groups: users, admin
    home: /home/ubuntu
    shell: /bin/bash
    ssh_authorized_keys:
      - ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQCda31EpeOd89hUB4zyl9p/QgmbUnwHMQ8p4xDV7pO2Tj9pH/thI/0U5BpAx3UdLpnPIExDID1NynooWWitmwQ84NKhl/2HYP/LyPETRRrPQvk7QWCXngbvKxQfrpWEiTFSRDwBEnTPsZr/ZsKTN7IFyXpcrpG3GB3GVqO+7VcwAbJMKoWX4OiuP1XhJblrM7gK5alSzz9H0eMn/o6F/aaLWhXL4rJacgNCkQv7fSyCqc+OboDxCJl2MB/ZEIb4nSkhNSEsliYQkbeUBVeLCtFy3SqrdTXcImB5YGfRsVUqcjYmTFOj/T+MZk3yvUQgU2uJSMZaC3IGSKYxGzmFDL45 aws-key
      - ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQC0WGP1EZykEtv5YGC9nMiPFW3U3DmZNzKFO5nEu6uozEHh4jLZzPNHSrfFTuQ2GnRDSt+XbOtTLdcj26+iPNiFoFha42aCIzYjt6V8Z+SQ9pzF4jPPzxwXfDdkEWylgoNnZ+4MG1lNFqa8aO7F62tX0Yj5khjC0Bs7Mb2cHLx1XZaxJV6qSaulDuBbLYe8QUZXkMc7wmob3PM0kflfolR3LE7LResIHWa4j4FL6r5cQmFlDU2BDPpKMFMGUfRSFiUtaWBNXFOWHQBC2+uKmuMPYP4vJC9sBgqMvPN/X2KyemqdMvdKXnCfrzadHuSSJYEzD64Cve5Zl9yVvY4AqyBD aws-key
ssh_pwauth: true
disable_root: false
packages:
  - mariadb-server
package_update: true
runcmd:
  - sudo mysql -sfu root -e "GRANT ALL ON *.* TO 'admin'@'%' IDENTIFIED BY'password' WITH GRANT OPTION;"
  - sudo sed -i 's/127.0.0.1/0.0.0.0/g' /etc/mysql/mariadb.conf.d/50-server.cnf
  - sudo systemctl restart mariadb.service