#cloud-config
package_update: true
users:
  - name: ubuntu
    sudo: ALL=(ALL) NOPASSWD:ALL
    groups: users, admin
    home: /home/ubuntu
    shell: /bin/bash
    ssh_authorized_keys:
      - ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQCda31EpeOd89hUB4zyl9p/QgmbUnwHMQ8p4xDV7pO2Tj9pH/thI/0U5BpAx3UdLpnPIExDID1NynooWWitmwQ84NKhl/2HYP/LyPETRRrPQvk7QWCXngbvKxQfrpWEiTFSRDwBEnTPsZr/ZsKTN7IFyXpcrpG3GB3GVqO+7VcwAbJMKoWX4OiuP1XhJblrM7gK5alSzz9H0eMn/o6F/aaLWhXL4rJacgNCkQv7fSyCqc+OboDxCJl2MB/ZEIb4nSkhNSEsliYQkbeUBVeLCtFy3SqrdTXcImB5YGfRsVUqcjYmTFOj/T+MZk3yvUQgU2uJSMZaC3IGSKYxGzmFDL45 aws-key
      - ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQC0WGP1EZykEtv5YGC9nMiPFW3U3DmZNzKFO5nEu6uozEHh4jLZzPNHSrfFTuQ2GnRDSt+XbOtTLdcj26+iPNiFoFha42aCIzYjt6V8Z+SQ9pzF4jPPzxwXfDdkEWylgoNnZ+4MG1lNFqa8aO7F62tX0Yj5khjC0Bs7Mb2cHLx1XZaxJV6qSaulDuBbLYe8QUZXkMc7wmob3PM0kflfolR3LE7LResIHWa4j4FL6r5cQmFlDU2BDPpKMFMGUfRSFiUtaWBNXFOWHQBC2+uKmuMPYP4vJC9sBgqMvPN/X2KyemqdMvdKXnCfrzadHuSSJYEzD64Cve5Zl9yVvY4AqyBD aws-key
ssh_pwauth: true
disable_root: false
packages:
  - apache2
  - curl
  - wget
  - php
  - libapache2-mod-php
  - php-mysqli
  - adminer
runcmd:
  - sudo a2enconf adminer
  - sudo systemctl restart apache2
write_files:
  - path: /var/www/html/info.php
    content: |
      <?php
      // Show all information, defaults to INFO_ALL
      phpinfo();
      ?>
    permissions: "0644"
  - path: /var/www/html/db.php
    content: |
      <?php
      //database
      $servername = "44.203.49.181";
      $username = "admin";
      $password = "password";
      $dbname = "mysql";

      // Create connection
      $conn = new mysqli($servername, $username, $password, $dbname);
      // Check connection
      if ($conn->connect_error) {
              die("Connection failed: " . $conn->connect_error);
      }

      $sql = "select Host, User from mysql.user;";
      $result = $conn->query($sql);
      while($row = $result->fetch_assoc()){
              echo($row["Host"] . " / " . $row["User"] . "<br />");
      }
      //var_dump($result);
      ?>
    permissions: "0644"
